### ISSUE TITLE
Exception occurred while fetching location data for tag 'Note10 Lite': Date string is empty

### ISSUE THREAD

**Issue by liamlain** [Vedeneb/HA-SmartThings-Find#17]
```
This error originated from a custom integration.

Logger: custom_components.smartthings_find.utils
Source: custom_components/smartthings_find/utils.py:377
integration: SmartThings Find (documentation, issues)
First occurred: 1:28:30 PM (32 occurrences)
Last logged: 2:31:32 PM

[lai's Note10 Lite] Exception occurred while fetching location data for tag 'Note10 Lite': Date string is empty
Traceback (most recent call last):
  File "/config/custom_components/smartthings_find/utils.py", line 377, in get_device_location
  File "/config/custom_components/smartthings_find/utils.py", line 534, in parse_stf_date
ValueError: Date string is empty
```

**Comment by Vedeneb** [comment]
Hi,
sorry for my late reply. Been realy busy the last few weeks. 
Is this still an issue? Does it happen every time the integration starts?
