### ISSUE TITLE
Exception occurred while fetching location data for tag 'Note10 Lite': time data '' does not match format '%Y%m%d%H%M%S'

### ISSUE THREAD

**Issue by liamlain** [Vedeneb/HA-SmartThings-Find#25]
last post the error was fixed,but recently i received  this error:

```
This error originated from a custom integration.

Logger: custom_components.smartthings_find.utils
Source: custom_components/smartthings_find/utils.py:377
integration: SmartThings Find (documentation, issues)
First occurred: August 27, 2024 at 11:13:47 PM (1436 occurrences)
Last logged: 11:41:26 PM

[lai's Note10 Lite] Exception occurred while fetching location data for tag 'lai's Note10 Lite': time data '' does not match format '%Y%m%d%H%M%S'
Traceback (most recent call last):
  File "/config/custom_components/smartthings_find/utils.py", line 377, in get_device_location
    utcDate = parse_stf_date(
              ^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_find/utils.py", line 543, in parse_stf_date
    return datetime.strptime(datestr, "%Y%m%d%H%M%S").replace(tzinfo=pytz.UTC)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y%m%d%H%M%S'
```

**Comment by PuckStar** [comment]
I have the same issue with the phone device. I tried disabling the phone device but the message still keeps appearing in the logs.
If anyone knows how to fix it, or how I can remove completely the phone device (as I'm just interested in Smart Tags tracking), that would be great!

`2024-08-31 12:29:23.751 ERROR (MainThread) [custom_components.smartthings_find.utils] [A50 van xxx] Exception occurred while fetching location data for tag 'A50 van xxx': time data '' does not match format '%Y%m%d%H%M%S'
Traceback (most recent call last):
  File "/config/custom_components/smartthings_find/utils.py", line 377, in get_device_location
    utcDate = parse_stf_date(
              ^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_find/utils.py", line 543, in parse_stf_date
    return datetime.strptime(datestr, "%Y%m%d%H%M%S").replace(tzinfo=pytz.UTC)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y%m%d%H%M%S'
`
