### ISSUE TITLE
error at setup

### ISSUE THREAD

**Issue by dedepene** [Vedeneb/HA-SmartThings-Find#8]
As soon as I try to set it up I get the following error:

> Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

Not sure if it's relevant but I'm currently on a supervised deployment:

![image](https://github.com/Vedeneb/HA-SmartThings-Find/assets/6883390/77d985f3-ff26-4c77-9291-8655d3dd06e3)

```
2024-06-01 12:57:06.715 DEBUG (MainThread) [custom_components.smartthings_find.config_flow] Entering login stage 1
2024-06-01 12:57:06.717 DEBUG (MainThread) [custom_components.smartthings_find.config_flow] Running login stage 1
2024-06-01 12:57:06.717 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 147, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 880, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 908, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_find/config_flow.py", line 66, in async_step_user
    return self.async_show_progress(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FlowHandler.async_show_progress() got an unexpected keyword argument 'progress_task'
2024-06-01 12:57:07.111 DEBUG (MainThread) [custom_components.smartthings_find.utils] Step 1: Pre-Login: Status Code: 200
2024-06-01 12:57:07.252 DEBUG (MainThread) [custom_components.smartthings_find.utils] Step 2: QR-Code URL: Status Code: 200
2024-06-01 12:57:07.252 INFO (MainThread) [custom_components.smartthings_find.utils] Extracted QR code URL: https://signin.samsung.com/key/******
2024-06-01 12:57:07.252 DEBUG (MainThread) [custom_components.smartthings_find.config_flow] Login stage 1 done
```

**Comment by dedepene** [comment]
follow up: as soon as I updated to the latest ha core the error is gone! apparently, the async_show_progress() method for the FlowHandler object has been updated and that's why passing the progress_task argument doesn't work on old core codebase

**Comment by Vedeneb** [comment]
Thanks for letting me know and glad you got it working. Do you know in which version the method was updated? So I could list this as the minimum required Home Assistant version.
